version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/usr/src'
      # Misc
      - '~/.config/composer:/.composer'
    restart: on-failure
    user: 1000:1000